## 사이킷런이란?
- 파이썬을 활용한 머신러닝 도구
- 데이터 분석(예측)을 위한 간단하고 효율적인 도구
- 누구나 쉽게 다양한 상황에서 활용 가능
- 오픈소스

## 사이킷런으로 할 수 있는 것
+ 분류(ex. 스팸)
+ 회귀(ex. 가격)
+ 클러스터링 (ex. 고객 세그먼트)
+ 차원축소 (ex. 변수(컬럼)의 수를 줄임)
+ 모델 선택 (ex. 모델 튜닝, 평가)
+ 전처리 (ex. 데이터 가공/변환)

### 데이터 불러오기
- 노드3에서 만든 'final_modudak.csv'와 동일

In [21]:
# 데이터 생성
import pandas as pd
import numpy as np
data = pd.read_csv('final_modudak.csv')
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [22]:
# 데이터 변경
data.loc[2, '원산지'] = '미국'

In [23]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

## 데이터 전처리: 범주형 데이터
- 레이블 인코딩
- 원핫 인코딩

In [24]:
# type확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


### 레이블(label) 인코딩 : 범주형 데이터를 하나의 시리즈로 정리
ex) 원산지 컬럼을 국내 = 0, 미국 = 1, 브라질 = 2로 하는 하나의 컬럼으로 생성

In [25]:
# 레이블(label) 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['원산지'])
le.transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [26]:
# fit_transform
le.fit_transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [27]:
# 데이터 변환
df['원산지'] = le.fit_transform(df['원산지'])
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

In [28]:
# '살찔까요' 라벨인코딩
df['살찔까요'] = le.fit_transform(df['살찔까요'])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

### 레이블 인코딩 (심화)
- 여러개 컬럼 한 번에 인코딩

In [29]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [30]:
# object 타입 선택 ['원산지','살찔까요']
# cols = ['원산지','살찔까요']            #방법 1.
cols = df.select_dtypes(include = 'object').columns  # 방법 2.

In [31]:
# 한번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [32]:
# 인코딩 결과 확인
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

### 원핫(one-hot) 인코딩 : 범주형 데이터를 갯수만큼 시리즈로 정리
ex) 원산지컬럼 - 원산지 별 자기 값만 1인 시리즈를 생성.

In [33]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [34]:
# 원핫인코딩
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse = False)
cat = ohe.fit_transform(df[['원산지']])
cat

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [35]:
# 카테고리
ohe.categories_

[array(['국내산', '미국', '브라질'], dtype=object)]

In [36]:
# 피처(컬럼) 이름과 카테고리
ohe.get_feature_names_out()

array(['원산지_국내산', '원산지_미국', '원산지_브라질'], dtype=object)

In [37]:
# 데이터프레임으로 변환
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_국내산  원산지_미국  원산지_브라질
0      1.0     0.0      0.0
1      0.0     0.0      1.0
2      0.0     1.0      0.0
3      1.0     0.0      0.0
4      0.0     0.0      1.0
5      1.0     0.0      0.0
6      1.0     0.0      0.0
7      1.0     0.0      0.0
8      1.0     0.0      0.0

In [38]:
# 데이터 프레임 합치기
df = pd.concat([df,df_cat], axis=1)
df

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0
5  13000  10  1400.0  국내산  yes      1.0     0.0      0.0
6  13000  10  1300.0  국내산  yes      1.0     0.0      0.0
7  12000  10  1000.0  국내산   no      1.0     0.0      0.0
8   9900  10  1000.0  국내산   no      1.0     0.0      0.0

In [39]:
# 기존 컬럼 삭제
df = df.drop(['원산지'], axis = 1)
df

가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   no      1.0     0.0      0.0
1  15000  12  1500.0  yes      0.0     0.0      1.0
2  14000   9  1600.0  yes      0.0     1.0      0.0
3  14000   9  1800.0  yes      1.0     0.0      0.0
4  14000  11  1300.0  yes      0.0     0.0      1.0
5  13000  10  1400.0  yes      1.0     0.0      0.0
6  13000  10  1300.0  yes      1.0     0.0      0.0
7  12000  10  1000.0   no      1.0     0.0      0.0
8   9900  10  1000.0   no      1.0     0.0      0.0

### 원핫 인코딩(심화)
- 여러 개 컬럼 한 번에 인코딩

In [40]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리', '원산지', '살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [41]:
# 원핫인코딩
cols = df.select_dtypes(include='object').columns
ohe = OneHotEncoder(sparse = False)
cat = ohe.fit_transform(df[cols])
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0      1.0     0.0      0.0      1.0       0.0
1      0.0     0.0      1.0      0.0       1.0
2      0.0     1.0      0.0      0.0       1.0
3      1.0     0.0      0.0      0.0       1.0
4      0.0     0.0      1.0      0.0       1.0
5      1.0     0.0      0.0      0.0       1.0
6      1.0     0.0      0.0      0.0       1.0
7      1.0     0.0      0.0      1.0       0.0
8      1.0     0.0      0.0      1.0       0.0

In [42]:
#데이터프레임 합치기
df = pd.concat([df, df_cat], axis= 1)
df.head()

가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0      0.0       1.0

In [43]:
# 컬럼 삭제
df = df.drop(cols, axis = 1)
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

#### [TIP] 원핫인코딩: 판다스 활용

In [44]:
# 활용할 데이터 선택
df = data[['가격','호수','칼로리', '원산지', '살찔까요']].copy()
df.head()

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes

In [45]:
# 판다스를 활용한 원핫 인코딩
# 데이터가 여러개가 되어서 train과 test의 컬럼의 수가 차이난다면 판다스 활용 불가.
df = pd.get_dummies(df)
df

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1
5  13000  10  1400.0        1       0        0        0         1
6  13000  10  1300.0        1       0        0        0         1
7  12000  10  1000.0        1       0        0        1         0
8   9900  10  1000.0        1       0        0        1         0

### 데이터 전처리: 수치형
- 표준화
- 정규화(Min-Max)

#### 표준화 (StandardScaler)
- 평균이 0, 분산이 1인 표준정규분포로 전환

In [46]:
# 원핫인코딩인 데이터
df.head()

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1

In [47]:
# StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [48]:
# StandardScaler 여러 변수에 적용
scaler = StandardScaler()
scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [49]:
# # 피처(컬럼)이름
cols = ['가격','호수','칼로리']
scaler = StandardScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

#### 민맥스 (MinMaxScaler)
- 0~1 사이 값으로 변환 (데이터 사이즈 축소)

In [50]:
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
cols = ['가격','호수','칼로리']
scaler = MinMaxScaler()
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수    칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.000000  0.666667  0.250        1       0        0        1         0
1  0.836066  1.000000  0.625        0       0        1        0         1
2  0.672131  0.000000  0.750        0       1        0        0         1
3  0.672131  0.000000  1.000        1       0        0        0         1
4  0.672131  0.666667  0.375        0       0        1        0         1
5  0.508197  0.333333  0.500        1       0        0        0         1
6  0.508197  0.333333  0.375        1       0        0        0         1
7  0.344262  0.333333  0.000        1       0        0        1         0
8  0.000000  0.333333  0.000        1       0        0        1         0

## 사이킷런에서 제공하는 데이터셋

### 유방암 데이터

In [51]:
# 사이킷런 데이터 불러오기
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
dataset

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [52]:
# 피처 이름 확인
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [53]:
# 타겟 확인
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [54]:
# 데이터 확인
dataset.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [55]:
# 데이터프레임으로 만들기
cancer_df = pd.DataFrame(data =dataset.data , columns = dataset.feature_names)
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [56]:
# 타겟 추가하기
cancer_df['target'] = dataset.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [57]:
# 데이터셋 확인 (load_*)
import sklearn.datasets
# sklearn.datasets.__all__ 하면 모든 데이터셋이 나옴.
# load로 되있는 부분이 불러올 수 있음.

### 당뇨병 데이터

In [58]:
# 당뇨병 데이터 불러오기
from sklearn.datasets import load_diabetes
dataset_diabetes = load_diabetes()
dataset_diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [59]:
# 데이터프레임으로 만들기
diabetes_df = pd.DataFrame(data = dataset_diabetes.data, columns = dataset_diabetes.feature_names)
diabetes_df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [60]:
# 타겟 추가하기
diabetes_df['target'] = dataset_diabetes.target
diabetes_df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  target  
0   -0.002592  0.019908 -0.017646   151.0  
1   -0.039493 -0.068330 -0.092204    75.0  
2   -0.002592  0.002864 -0.025930   141.0  
3    0.034309  0.022692 -0.009362   206.0  
4   -0.002592 -0.031991 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018118  0.044485   104.0  
439 -0.011080 -0.046879  0.015491   132.0  
440  0.026560  0.044528 -0.025930   220.0  
441 -0.039493 -0.004220  0.003064    57.0  

[442 rows x 11 columns]

## 머신러닝: 분류
### 검증데이터 분리

In [66]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    cancer_df.drop('target', axis = 1 ), cancer_df['target'], test_size= 0.3, random_state= 1004)

In [67]:
# train 데이터 확인(X)
X_train.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
350       11.660         17.07           73.70      421.0          0.07561   
384       13.280         13.72           85.79      541.8          0.08363   
7         13.710         20.83           90.20      577.9          0.11890   
557        9.423         27.88           59.26      271.3          0.08123   
49        13.490         22.30           86.91      561.0          0.08752   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
350           0.03630        0.008306              0.01162         0.1671   
384           0.08575        0.050770              0.02864         0.1617   
7             0.16450        0.093660              0.05985         0.2196   
557           0.04971        0.000000              0.00000         0.1742   
49            0.07698        0.047510              0.03384         0.1809   

     mean fractal dimension  ...  worst radius  worst texture  \
350                 0.05731  ...         13.28          19.74   
384                 0.05594  ...         14.24          17.37   
7                   0.07451  ...         17.06          28.14   
557                 0.06059  ...         10.49          34.24   
49                  0.05718  ...         15.15          31.82   

     worst perimeter  worst area  worst smoothness  worst compactness  \
350            83.61       542.5           0.09958            0.06476   
384            96.59       623.7           0.11660            0.26850   
7             110.60       897.0           0.16540            0.36820   
557            66.50       330.6           0.10730            0.07158   
49             99.00       698.8           0.11620            0.17110   

     worst concavity  worst concave points  worst symmetry  \
350          0.03046               0.04262          0.2731   
384          0.28660               0.09173          0.2736   
7            0.26780               0.15560          0.3196   
557          0.00000               0.00000          0.2475   
49           0.22820               0.12820          0.2871   

     worst fractal dimension  
350                  0.06825  
384                  0.07320  
7                    0.11510  
557                  0.06969  
49                   0.06917  

[5 rows x 30 columns]

In [68]:
# 학습 데이터 확인(Y)
Y_train.head()

350    1
384    1
7      0
557    1
49     1
Name: target, dtype: int64

In [69]:
# 데이터 크기
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((398, 30), (171, 30), (398,), (171,))

### 의사결정나무(DecisionTree)

In [72]:
# 머신러닝(분류)
from sklearn.tree import DecisionTreeClassifier

# 모델 선택
model = DecisionTreeClassifier()
# 학습
model.fit(X_train,Y_train)
# 예측
pred = model.predict(X_test)
pred

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

#### 평가(accuracy)

In [73]:
# 정확도 accuracy_score(실제값, 예측값)
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, pred)

0.8947368421052632

## 머신러닝: 회귀

### 검증데이터 분리

In [74]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    diabetes_df.drop('target', axis = 1 ), diabetes_df['target'], test_size= 0.3, random_state= 1004)

In [75]:
# train 데이터 확인 (X)
X_train.head()

age       sex       bmi        bp        s1        s2        s3  \
232  0.012648  0.050680  0.000261 -0.011409  0.039710  0.057245 -0.039719   
81   0.012648  0.050680 -0.022373 -0.029771  0.010815  0.028435 -0.021311   
227  0.067136  0.050680 -0.029918  0.057449 -0.000193 -0.015719  0.074412   
334 -0.060003  0.050680 -0.047163 -0.022885 -0.071743 -0.057681 -0.006584   
83  -0.038207 -0.044642  0.009961 -0.046985 -0.059359 -0.052983 -0.010266   

           s4        s5        s6  
232  0.056081  0.024053  0.032059  
81   0.034309 -0.006080 -0.001078  
227 -0.050564 -0.038459  0.007207  
334 -0.039493 -0.062913 -0.054925  
83  -0.039493 -0.015998 -0.042499

In [76]:
# 학습 데이터 확인(Y)
Y_train.head()

232    259.0
81      51.0
227    108.0
334     72.0
83     210.0
Name: target, dtype: float64

In [77]:
# 데이터 크기
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((309, 10), (133, 10), (309,), (133,))

### 선형회귀(LinearRegression)

In [78]:
# 머신러닝(회귀)
from sklearn.linear_model import LinearRegression

# 모델 선택
model = LinearRegression()
# 학습
model.fit(X_train,Y_train)
# 예측
pred = model.predict(X_test)
pred

array([128.42584096, 135.0870178 , 154.78166657, 106.09435851,
       149.54313889, 165.32784413, 140.28955883, 167.95778147,
        69.4503107 , 189.42664051, 144.9847161 , 150.11273979,
       211.16078839, 108.59060526, 160.38284395, 154.09983174,
       198.78261008, 101.15867269, 165.82927955, 196.03539157,
       147.16334011, 108.25672705, 207.28165472, 127.53118326,
       181.85939663, 228.49956035,  86.59826865, 155.35000645,
       182.49645024, 182.96618563, 207.62865615, 199.81160132,
       157.36018064,  61.82420828,  88.11382212,  95.75044874,
       134.03529608,  85.95868919, 177.696808  , 249.40294124,
       171.77254108, 204.7152808 , 239.12264861,  89.25163253,
       244.20493803, 180.3631026 , 161.10419087, 119.1476007 ,
       102.82444201, 153.35453384, 129.06516018, 208.80060788,
       107.93804188, 138.812454  , 166.04360408,  86.04372546,
       181.03333757, 117.98035042,  79.04611318, 127.20684737,
       194.06146795, 205.13560483, 233.85068191,  48.53

### 평가(mse)

In [79]:
# 정확도 mean_squared_error( 실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(Y_test, pred)

3229.4396061827333